import type { Metadata } from 'next';
import './globals.css';
import SidebarWrapper from './components/SidebarWrapper/SidebarWrapper';
import { SidebarProvider } from './components/SidebarProvider/sidebarProvider';

export const metadata: Metadata = {
  title: 'Jakarta Justice Forum',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="">
      <head>
        <meta property="og:image" content="/img/logo/logo-og.png" />
        <meta property="og:type" content="website" />
        <link rel="icon" href="/img/logo/logo.svg" sizes="any" />
      </head>
      <body className="w-full h-full overflow-x-hidden dark:bg-blackJ bg-white">
        <SidebarProvider>
          <SidebarWrapper>{children}</SidebarWrapper>
        </SidebarProvider>
      </body>
    </html>
  );
}
